language: python
sudo: false
python:
 - "3.5"
 - "3.4"
 - "3.3"
 - "2.7"
env:
 - DJANGO_VERSION=1.8.16
 - DJANGO_VERSION=1.9.11
 - DJANGO_VERSION=1.10.3
install:
 - pip install -q Django==$DJANGO_VERSION
matrix:
 exclude:
   - python: "3.3"
     env: DJANGO_VERSION=1.9.11
   - python: "3.3"
     env: DJANGO_VERSION=1.10.3
script:
 - coverage run setup.py test